language: python
python: 2.7
install:
    - sudo apt-get install fonts-ipafont-gothic libjpeg8-dev libfreetype6-dev
    - pip install virtualenv
    - virtualenv .
    - . bin/activate
    - pip install --upgrade wheel
    - pip install --upgrade --use-wheel docutils pip tox virtualenv
    - pip install --upgrade --use-wheel --pre -r requirements.txt
script:
    - echo "[s3]" > $HOME/.boto
    - echo "calling_format = boto.s3.connection.OrdinaryCallingFormat" >> $HOME/.boto
    - make -C sources/en html
    - make -C sources/ja gettext html
    - boto-rsync -g public-read --delete _build/en/html s3://blockdiag.com/en
    - boto-rsync -g public-read --delete _build/ja/html s3://blockdiag.com/ja
