application: blockdiag-com
version: 1
runtime: python
api_version: 1
handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: (.*)/
  static_files: \1/index.html
  upload: (.*)/index.html
- url: /(.*)
  static_files: \1
  upload: (.*)
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^bin/(.*)$
- ^develop-eggs/(.*)$
- ^eggs/(.*)$
- ^parts/(.*)$
